#!/usr/bin/make
##########################################################################
# FILE IDENTIFICATION
#
#  Name:         Makefile
#  Purpose:      Makefile for CLSQL tests
#  Programer:    Kevin M. Rosenberg
#  Date Started: Mar 2002
#
# This file is part of CLSQL
#
# CLSQL users are granted the rights to distribute and use this software
# as governed by the terms of the Lisp Lesser GNU Public License
# (http://opensource.franz.com/preamble.html), also known as the LLGPL.
##########################################################################


SUBDIRS=

include ../Makefile.common

.PHONY: distclean
distclean: clean

